name: Build AQWAX VST3

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout AQWAX
        uses: actions/checkout@v4

      - name: Install JUCE
        shell: pwsh
        run: |
          git clone --depth 1 --branch 8.0.15 https://github.com/juce-framework/JUCE.git "$env:GITHUB_WORKSPACE\JUCE"

      - name: Check project
        shell: pwsh
        run: |
          Write-Host "=== PROJECT ==="
          Get-ChildItem "$env:GITHUB_WORKSPACE"

          Write-Host "=== CMAKE ==="
          Get-Item "$env:GITHUB_WORKSPACE\CMakeLists.txt"

          Write-Host "=== JUCE ==="
          Get-Item "$env:GITHUB_WORKSPACE\JUCE\CMakeLists.txt"

          Write-Host "=== SOURCE ==="
          Get-ChildItem "$env:GITHUB_WORKSPACE\Source"

      - name: Configure CMake
        shell: pwsh
        run: |
          cmake `
            -S "$env:GITHUB_WORKSPACE" `
            -B "$env:GITHUB_WORKSPACE\build" `
            -G "Visual Studio 17 2022" `
            -A x64 `
            -DJUCE_DIR="$env:GITHUB_WORKSPACE\JUCE"

      - name: Build AQWAX
        shell: pwsh
        run: |
          cmake `
            --build "$env:GITHUB_WORKSPACE\build" `
            --config Release `
            --parallel

      - name: Find AQWAX VST3
        shell: pwsh
        run: |
          $plugin = Get-ChildItem `
            "$env:GITHUB_WORKSPACE\build" `
            -Filter "AQWAX.vst3" `
            -Recurse `
            -Directory |
            Select-Object -First 1

          if (-not $plugin) {
            Write-Host "AQWAX.vst3 not found."
            Get-ChildItem "$env:GITHUB_WORKSPACE\build" -Recurse
            exit 1
          }

          Write-Host "Found:"
          Write-Host $plugin.FullName

          New-Item -ItemType Directory `
            -Force `
            -Path "$env:GITHUB_WORKSPACE\release"

          Copy-Item `
            $plugin.FullName `
            "$env:GITHUB_WORKSPACE\release\AQWAX.vst3" `
            -Recurse

      - name: Package VST3
        shell: pwsh
        run: |
          Compress-Archive `
            -Path "$env:GITHUB_WORKSPACE\release\AQWAX.vst3" `
            -DestinationPath "$env:GITHUB_WORKSPACE\AQWAX-v1.0-Windows-VST3.zip" `
            -Force

      - name: Upload VST3
        uses: actions/upload-artifact@v4
        with:
          name: AQWAX-v1.0-Windows-VST3
          path: AQWAX-v1.0-Windows-VST3.zip
